services:
  - type: web
    name: shopsense-recommender
    runtime: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python backend/utils/data_loader.py &&
      python backend/utils/generate_synthetic_users.py &&
      python models/content_based.py &&
      python models/association_rules.py &&
      python models/popularity.py &&
      python models/sentiment_analysis.py &&
      python models/collaborative_filtering.py
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT